### PR TITLE
Implement create/update/delete of a subnet

### PR DESCRIPTION
**Pull request by mgusek-interhyp**
Implements create/update/delete of a subnet with small bugfixes

### CODE REVIEW

**Comment by lhw** [comment]
I'll have a look at this. Did you test this in your environment?

**Comment by mgusek-interhyp** [comment]
Yes, it work's in my environment.

**Comment by lhw** [comment]
I did some local testing and it seems to work fine. I will have to add some more fields to subnets as our subnets include more features but everything here works fine.

**Comment by lhw** [comment]
Could you squash the commits before merging?

**Comment by lhw** [comment]
Nevermind that works on github

**Pull request merged**
