### PR TITLE
Add usergroup management

### PR DESCRIPTION
**Pull request by Fodoj**

### CODE REVIEW

**Comment by Fodoj** [comment]
Depends on https://github.com/HanseMerkur/terraform-provider-foreman/pull/25 to be merged first

**Comment by lhw** [comment]
Could you split out the wrapjson change into a PR of its own? That makes it clearer what changes were made

**Comment by Fodoj** [comment]
@lhw https://github.com/HanseMerkur/terraform-provider-foreman/pull/27/files

**Comment by Fodoj** [comment]
@lhw I've resolved conflicts here

**Pull request merged**
